# Generated by Django 5.2.18 on 2026-10-07 07:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Manufacturer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Производитель')),
            ],
            options={
                'verbose_name': 'производитель',
                'verbose_name_plural': 'производители',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('make', models.CharField(max_length=80, verbose_name='Марка автомобиля')),
                ('model', models.CharField(max_length=120, verbose_name='Модель / поколение')),
                ('engine', models.CharField(blank=True, max_length=120, verbose_name='Двигатель / модификация')),
                ('year_from', models.PositiveSmallIntegerField(verbose_name='Год с')),
                ('year_to', models.PositiveSmallIntegerField(blank=True, null=True, verbose_name='Год по')),
            ],
            options={
                'verbose_name': 'автомобиль',
                'verbose_name_plural': 'автомобили',
                'ordering': ['make', 'model', 'year_from'],
                'constraints': [models.CheckConstraint(condition=models.Q(('year_to__isnull', True), ('year_to__gte', models.F('year_from')), _connector='OR'), name='vehicle_year_range')],
            },
        ),
        migrations.CreateModel(
            name='Part',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=80, verbose_name='Артикул')),
                ('article_key', models.CharField(db_index=True, editable=False, max_length=80)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('category', models.CharField(blank=True, max_length=100, verbose_name='Категория')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('source', models.CharField(blank=True, max_length=255, verbose_name='Источник данных')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.manufacturer', verbose_name='Производитель')),
                ('vehicles', models.ManyToManyField(blank=True, to='catalog.vehicle', verbose_name='Применяемость')),
            ],
            options={
                'verbose_name': 'запчасть',
                'verbose_name_plural': 'запчасти',
                'ordering': ['manufacturer__name', 'article'],
            },
        ),
        migrations.CreateModel(
            name='CrossReference',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relation_code', models.CharField(max_length=80, verbose_name='Код отношения')),
                ('relation_name', models.CharField(max_length=120, verbose_name='Название отношения')),
                ('direction', models.CharField(choices=[('forward', 'forward'), ('reverse', 'reverse')], max_length=16, verbose_name='Направление источника')),
                ('weight', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Вес из источника')),
                ('rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True, verbose_name='Рейтинг из источника')),
                ('last_seen_at', models.DateTimeField(blank=True, null=True, verbose_name='Дата из источника')),
                ('source', models.CharField(max_length=255, verbose_name='Источник / файл')),
                ('related_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_to', to='catalog.part', verbose_name='Связанная деталь')),
                ('source_part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='references_from', to='catalog.part', verbose_name='Исходная деталь')),
            ],
            options={
                'verbose_name': 'связь из каталога',
                'verbose_name_plural': 'связи из каталога',
                'constraints': [models.UniqueConstraint(fields=('source_part', 'related_part', 'relation_code', 'direction'), name='unique_source_reference')],
            },
        ),
        migrations.CreateModel(
            name='Analogue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(max_length=255, verbose_name='Источник / каталог')),
                ('note', models.TextField(blank=True, verbose_name='Условия замены / примечание')),
                ('verified', models.BooleanField(default=False, verbose_name='Проверено специалистом')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_a', to='catalog.part', verbose_name='Деталь 1')),
                ('part_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='links_b', to='catalog.part', verbose_name='Деталь 2')),
            ],
            options={
                'verbose_name': 'связь аналогов',
                'verbose_name_plural': 'связи аналогов',
                'constraints': [models.UniqueConstraint(fields=('part_a', 'part_b'), name='unique_analogue_pair'), models.CheckConstraint(condition=models.Q(('part_a__lt', models.F('part_b'))), name='ordered_distinct_analogue_pair')],
            },
        ),
        migrations.AddConstraint(
            model_name='part',
            constraint=models.UniqueConstraint(fields=('manufacturer', 'article_key'), name='unique_manufacturer_article'),
        ),
    ]
